version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    labels:
      - "pnpm dependencies"
    target-branch: "main"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    labels:
      - "github actions"
    target-branch: "main"
    open-pull-requests-limit: 10
