stages:
  - test
  - audit
  - build
  - scan
  - upload
  - release

default:
  image: "${ARTIFACTORY_SERVER}/sds/sdd-common-ci:2026.9.3@sha256:f4e479e35c1155e8422bec6d23315f5e6fae997188c6d41076600a6804ab9089"

# Release process
include:
  - project: "sds-dev/releases"
    ref: main
    file: "releases.yml"

#
# Code testing
#
.test-base:
  stage: test
  tags:
    - sds-test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - pnpm install

code-style:
  extends: .test-base
  script:
    - pnpm run lint:check

format-style:
  extends: .test-base
  script:
    - pnpm run format:check

type-check:
  extends: .test-base
  script:
    - pnpm run tsc

unittest:
  extends: .test-base
  script:
    - pnpm run test:coverage

#
# JFrog audit for pnpm
#
jfrog-pnpm-audit:
  stage: audit
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $GITLAB_USER_NAME != "renovate-bot"'
      when: always
      variables:
        WATCH: sds-watch
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $GITLAB_USER_NAME == "renovate-bot"'
      variables:
        WATCH: sds-renovate
  tags:
    - sds-test
  before_script:
    - jf config import "${JF_CONFIG_READ_ONLY}"
  script:
    - jf audit --pnpm --extended-table --watches=$WATCH

#
# Docker image build
#
build-image:
  stage: build
  tags:
    - sds-build
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      variables:
        IMAGE_TAG: $CI_DEFAULT_BRANCH_SLUG
    - if: "$CI_COMMIT_TAG"
      variables:
        IMAGE_TAG: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        IMAGE_TAG: $CI_COMMIT_REF_SLUG
  variables:
    REGISTRY_IMAGE: ${CONTAINER_REGISTRY_ADDRESS}/sds/sd-submit-ui:${IMAGE_TAG}
  before_script:
    - pnpm config list
  script:
    - echo "Building image sd-submit-ui:${IMAGE_TAG}"
    - >
      docker buildx build -t "${REGISTRY_IMAGE}"
      --secret id=auth_file,src=$HOME/.config/pnpm/auth.ini
      --secret id=npm_token,env=ARTIFACTORY_NPM_TOKEN
      --iidfile iid.out -f Dockerfile .
    - docker push "${REGISTRY_IMAGE}"
    # Save digest as a dotenv artifact
    - echo "IMAGE_DIGEST=$(cat iid.out)" >> build.env
  artifacts:
    reports:
      dotenv: build.env

#
# Docker image scan
#
scan-image:
  stage: scan
  tags:
    - sds-test
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      variables:
        WATCH: sds-watch
        IMAGE_TAG: $CI_DEFAULT_BRANCH_SLUG
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $GITLAB_USER_NAME != "renovate-bot"'
      variables:
        WATCH: sds-watch
        IMAGE_TAG: $CI_COMMIT_REF_SLUG
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $GITLAB_USER_NAME == "renovate-bot"'
      variables:
        WATCH: sds-renovate
        IMAGE_TAG: $CI_COMMIT_REF_SLUG
  variables:
    REGISTRY_IMAGE: ${CONTAINER_REGISTRY_ADDRESS}/sds/sd-submit-ui:${IMAGE_TAG}
  before_script:
    - jf config import "${JF_CONFIG_READ_ONLY}"
  script:
    - docker pull "${REGISTRY_IMAGE}@${IMAGE_DIGEST}"
    - docker tag "${REGISTRY_IMAGE}@${IMAGE_DIGEST}" "${REGISTRY_IMAGE}"
    - jf docker scan --extended-table --watches=$WATCH "${REGISTRY_IMAGE}"

#
# Docker image push
#
upload-image:
  stage: upload
  tags:
    - sds-upload
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: never
    - if: "$CI_COMMIT_TAG"
      variables:
        IMAGE_TAG: $CI_COMMIT_TAG
        JFROG_CLI_BUILD_NUMBER: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
      allow_failure: true
      variables:
        IMAGE_TAG: $CI_COMMIT_REF_SLUG
        JFROG_CLI_BUILD_NUMBER: $CI_COMMIT_REF_SLUG
  variables:
    REGISTRY_IMAGE: ${CONTAINER_REGISTRY_ADDRESS}/sds/sd-submit-ui:${IMAGE_TAG}
    JFROG_CLI_BUILD_NAME: sd-submit-ui
    JFROG_CLI_BUILD_PROJECT: sds
  before_script:
    - jf config import "${JF_CONFIG}"
  script:
    - echo "Pushing image sd-submit-ui:${IMAGE_TAG}"
    - docker pull "${REGISTRY_IMAGE}@${IMAGE_DIGEST}"
    - docker tag "${REGISTRY_IMAGE}@${IMAGE_DIGEST}" "${ARTIFACTORY_SERVER}/${REGISTRY_IMAGE#*/}"
    - jf docker push $JFROG_ARGS "${ARTIFACTORY_SERVER}/${REGISTRY_IMAGE#*/}"
    - jf rt build-publish

release-job:
  extends: .automated-release
  release:
    description: $(cat release_changes.md)
    assets:
      links:
        - name: "${ARTIFACTORY_SERVER}/sds/sd-submit-ui:${RELEASE_VERSION}"
          url: "https://${ARTIFACTORY_SERVER}/artifactory/sds-docker/sds/sd-submit-ui/${RELEASE_VERSION}"
          link_type: image
