#=========================
FROM node:22-trixie-slim@sha256:7b8a0c89c54499bee567618f96578e1a12a800f062fbdbfd1fb6a443fa6f6284
#=========================

RUN npm install -g pnpm

WORKDIR /home/node

COPY . .

RUN pnpm install --frozen-lockfile

# This is just reminding the port in use inside a container
EXPOSE 3000

RUN chown -R node:node /home/node

RUN pnpm exec playwright install --with-deps

USER node

RUN  pnpm exec playwright install

CMD ["pnpm", "start:headless"]
