#=========================
FROM node:22-trixie-slim
#=========================

RUN npm install -g pnpm

WORKDIR /home/node

COPY . .

RUN pnpm install --frozen-lockfile

# This is just reminding the port in use inside a container
EXPOSE 3000

RUN chown -R node:node /home/node

CMD ["pnpm", "start:headless"]
