allowBuilds:
  esbuild: true
  msw: false

overrides:
  "elliptic@<6.6.1": "6.6.1"
  "sha.js@<2.4.12": "2.4.12"
  "cipher-base@<1.0.5": "1.0.7"
  "pbkdf2@<3.1.3": "3.1.6"
  "axios@<1.15.2": "1.15.2"

registries:
  https://artifactory.ci.csc.fi/artifactory/api/npm/sds-npm/:
    scopes: ["@"]
    prefix: npmjs
  https://artifactory.ci.csc.fi/artifactory/api/npm/sds-npm-jsr-remote/:
    scopes: ["@jsr"]
  https://artifactory.ci.csc.fi/artifactory/api/npm/sds-npm-github-remote/:
    prefix: gh

publicHoistPattern:
  - "*@types*"
