name: Code style check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["20"]
    name: ESLint check
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - name: Install dependencies
        run: |
          pnpm install
      - name: Run code style check with ESLint
        run: |
          pnpm run lint:check
