name: Code style check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14"]
    name: ESLint check
    steps:
      - uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          npm ci
      - name: Run code style check with ESLint
        run: |
          npm run lint:check
