name: End-to-end tests

on: [push] # Change to pull_request when up & running

jobs:
  cypress-e2e-chrome-headless:
    name: Cypress e2e on Chrome
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14"]
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          start: npm start
          browser: chrome
  cypress-e2e-firefox:
    name: Cypress e2e on Firefox
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14"]
    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73
      options: --user 1001 # The only way to run Firefox is to use --user 1001
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          start: npm start
          browser: firefox
