name: Non-js file formatting (json, md etc.) check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16"]
    name: Prettier check
    steps:
      - uses: actions/checkout@v4
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          npm ci
      - name: Run format check with Prettier
        run: |
          npm run format:check
